# TV Script Generation
In this project, you'll generate your own [Simpsons](https://en.wikipedia.org/wiki/The_Simpsons) TV scripts using RNNs.  You'll be using part of the [Simpsons dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data) of scripts from 27 seasons.  The Neural Network you'll build will generate a new TV script for a scene at [Moe's Tavern](https://simpsonswiki.com/wiki/Moe's_Tavern).
## Get the Data
The data is already provided for you.  You'll be using a subset of the original dataset.  It consists of only the scenes in Moe's Tavern.  This doesn't include other versions of the tavern, like "Moe's Cavern", "Flaming Moe's", "Uncle Moe's Family Feed-Bag", etc..

In [1]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper

data_dir = './data/simpsons/moes_tavern_lines.txt'
text = helper.load_data(data_dir)
# Ignore notice, since we don't use it for analysing the data
text = text[81:]
print(text)

Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.


Moe_Szyslak: Ah, isn't that nice. Now, there is a politician who cares.
Barney_Gumble: If I ever vote, it'll be for him. (BELCH)


Barney_Gumble: Hey Homer, how's your neighbor's store doing?
Homer_Simpson: Lousy. He just sits there all day. He'd have a great job if he didn't own the place. (CHUCKLES)


## Explore the Data
Play around with `view_sentence_range` to view different parts of the data.

In [2]:
#play with the range here
view_sentence_range = (0, 10)

"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import numpy as np

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in text.split()})))
scenes = text.split('\n\n')#two new lines indicate a new scene
print('Number of scenes: {}'.format(len(scenes)))
sentence_count_scene = [scene.count('\n') for scene in scenes]
print('Average number of sentences in each scene: {}'.format(np.average(sentence_count_scene)))

sentences = [sentence for scene in scenes for sentence in scene.split('\n')]
print('Number of lines: {}'.format(len(sentences)))
word_count_sentence = [len(sentence.split()) for sentence in sentences]
print('Average number of words in each line: {}'.format(np.average(word_count_sentence)))

print()
print('The sentences {} to {}:'.format(*view_sentence_range))
print('\n'.join(text.split('\n')[view_sentence_range[0]:view_sentence_range[1]]))



Dataset Stats
Roughly the number of unique words: 11492
Number of scenes: 262
Average number of sentences in each scene: 15.248091603053435
Number of lines: 4257
Average number of words in each line: 11.50434578341555

The sentences 0 to 10:
Moe_Szyslak: (INTO PHONE) Moe's Tavern. Where the elite meet to drink.
Bart_Simpson: Eh, yeah, hello, is Mike there? Last name, Rotch.
Moe_Szyslak: (INTO PHONE) Hold on, I'll check. (TO BARFLIES) Mike Rotch. Mike Rotch. Hey, has anybody seen Mike Rotch, lately?
Moe_Szyslak: (INTO PHONE) Listen you little puke. One of these days I'm gonna catch you, and I'm gonna carve my name on your back with an ice pick.
Moe_Szyslak: What's the matter Homer? You're not your normal effervescent self.
Homer_Simpson: I got my problems, Moe. Give me another one.
Moe_Szyslak: Homer, hey, you should not drink to forget your problems.
Barney_Gumble: Yeah, you should only drink to enhance your social skills.




## Implement Preprocessing Functions
The first thing to do to any dataset is preprocessing.  Implement the following preprocessing functions below:
- Lookup Table
- Tokenize Punctuation

### Lookup Table
To create a word embedding, you first need to transform the words to ids.  In this function, create two dictionaries:
- Dictionary to go from the words to an id, we'll call `vocab_to_int`
- Dictionary to go from the id to word, we'll call `int_to_vocab`

Return these dictionaries in the following tuple `(vocab_to_int, int_to_vocab)`

In [3]:
import numpy as np
import problem_unittests as tests
from collections import Counter
#assign ints ascending with 0 as most common (ie. the)
#import utils
#############################################
!pip install -U tensorflow==1.3
################################################
def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts.  The first dict....
    """
    words = text #.split()#split text into individual words
    word_counts = Counter(words)
    sorted_vocab = sorted(word_counts, key=word_counts.get, reverse=True)
    int_to_vocab = {ii: word for ii, word in enumerate(sorted_vocab)}
    vocab_to_int = {word: ii for ii, word in int_to_vocab.items()}

    return vocab_to_int, int_to_vocab
    
    
#######################################################################################

v_to_int, int_to_v = create_lookup_tables(text)
print(v_to_int)
print(int_to_v)

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_create_lookup_tables(create_lookup_tables)

    100% |████████████████████████████████| 43.6MB 31kB/s eta 0:00:011  17% |█████▋                          | 7.7MB 351kB/s eta 0:01:42    21% |███████                         | 9.5MB 661kB/s eta 0:00:52    22% |███████▏                        | 9.8MB 2.6MB/s eta 0:00:13    22% |███████▎                        | 9.9MB 653kB/s eta 0:00:52    37% |████████████                    | 16.5MB 1.1MB/s eta 0:00:26    58% |██████████████████▉             | 25.6MB 321kB/s eta 0:00:56    83% |██████████████████████████▋     | 36.2MB 569kB/s eta 0:00:13    88% |████████████████████████████▎   | 38.5MB 554kB/s eta 0:00:10    95% |██████████████████████████████▋ | 41.7MB 699kB/s eta 0:00:03
Requirement already up-to-date: numpy>=1.11.0 in /home/nobu/anaconda3/lib/python3.6/site-packages (from tensorflow==1.3)
    100% |████████████████████████████████| 1.6MB 385kB/s ta 0:00:01
Requirement already up-to-date: wheel>=0.26 in /home/nobu/anaconda3/lib/python3.6/site-packages (from tensorflow==1.3)
Requi

### Tokenize Punctuation
We'll be splitting the script into a word array using spaces as delimiters.  However, punctuations like periods and exclamation marks make it hard for the neural network to distinguish between the word "bye" and "bye!".

Implement the function `token_lookup` to return a dict that will be used to tokenize symbols like "!" into "||Exclamation_Mark||".  Create a dictionary for the following symbols where the symbol is the key and value is the token:
- Period ( . )
- Comma ( , )
- Quotation Mark ( " )
- Semicolon ( ; )
- Exclamation mark ( ! )
- Question mark ( ? )
- Left Parentheses ( ( )
- Right Parentheses ( ) )
- Dash ( -- )
- Return ( \n )

This dictionary will be used to token the symbols and add the delimiter (space) around it.  This separates the symbols as it's own word, making it easier for the neural network to predict on the next word. Make sure you don't use a token that could be confused as a word. Instead of using the token "dash", try using something like "||dash||".

In [4]:
def token_lookup():
    """
    Generate a dict to turn punctuation into a token.
    :return: Tokenize dictionary where the key is the punctuation and the value is the token
    """
    # TODO: Implement Function
    token_to_alpha={'.':'<PERIOD>', ',':'<COMMA>', 
                    '"':'QUOTATION_MARK',';':'SEMICOLON',
                   '!':'EXCLAMATION_MARK', '?':'QUESTION_MARK',
                    '(':'LEFT_PAREN', ')':'RIGHT_PAREN',
                   '--':'DDDAAASSSH', '\n':'RRRETTTURRRN'}
    
    
    return token_to_alpha
#########################################################


#############################################################################

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_tokenize(token_lookup)#is returned to token_dict capture variable

Tests Passed


## Preprocess all the data and save it
Running the code cell below will preprocess all the data and save it to file.

In [5]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Preprocess Training, Validation, and Testing Data
helper.preprocess_and_save_data(data_dir, token_lookup, create_lookup_tables)

# Check Point
This is your first checkpoint. If you ever decide to come back to this notebook or have to restart the notebook, you can start from here. The preprocessed data has been saved to disk.

In [6]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import helper
import numpy as np
import problem_unittests as tests

int_text, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
#print(int_text)#text as ints so this is the input

## Build the Neural Network
You'll build the components necessary to build a RNN by implementing the following functions below:
- get_inputs
- get_init_cell
- get_embed
- build_rnn
- build_nn
- get_batches

### Check the Version of TensorFlow and Access to GPU

In [7]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from distutils.version import LooseVersion
import warnings
import tensorflow as tf

# Check TensorFlow Version
assert LooseVersion(tf.__version__) >= LooseVersion('1.0'), 'Please use TensorFlow version 1.0 or newer'
print('TensorFlow Version: {}'.format(tf.__version__))

# Check for a GPU
if not tf.test.gpu_device_name():
    warnings.warn('No GPU found. Please use a GPU to train your neural network.')
else:
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
    


TensorFlow Version: 1.0.0


/home/nobu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: UserWarning: No GPU found. Please use a GPU to train your neural network.
  


### Input
Implement the `get_inputs()` function to create TF Placeholders for the Neural Network.  It should create the following placeholders:
- Input text placeholder named "input" using the [TF Placeholder](https://www.tensorflow.org/api_docs/python/tf/placeholder) `name` parameter.
- Targets placeholder
- Learning Rate placeholder

Return the placeholders in the following tuple `(Input, Targets, LearningRate)`

In [8]:
def get_inputs():
    """
    Create TF Placeholders for input, targets, and learning rate.
    :return: Tuple (input, targets, learning rate)
    """
    # TODO: Implement Function
    #actually just need to make these, nothing complex like picking data to feed in
    # Declare placeholders we'll feed into the graph, use None for shape so can change later
    Input = tf.placeholder(tf.int32, [None, None], name='input')
    #targets is one word shifted over since we're trying to predict next word
    #targets=int_text[1:]
    #last word should be the first word?  
    #targets[-1]=int_text[0]
    Targets = tf.placeholder(tf.int32, [None, None], name='targets')
    
    #LearningRate placeholder
    LearningRate =tf.placeholder(tf.float32, [], name='LearningRate')
    
    
    return Input, Targets, LearningRate

###refer here: https://www.tensorflow.org/programmers_guide/tensors    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_inputs(get_inputs)

Tests Passed


### Build RNN Cell and Initialize
Stack one or more [`BasicLSTMCells`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell) in a [`MultiRNNCell`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell).
- The Rnn size should be set using `rnn_size`
- Initalize Cell State using the MultiRNNCell's [`zero_state()`](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/MultiRNNCell#zero_state) function
    - Apply the name "initial_state" to the initial state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the cell and initial state in the following tuple `(Cell, InitialState)`

In [9]:
def get_init_cell(batch_size, rnn_size):
    """
    Create an RNN Cell and initialize it.
    :param batch_size: Size of batches
    :param rnn_size: Size of RNNs
    :return: Tuple (cell, initialize state)
    """
    # TODO: Implement Function
    lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
    #for cell ([lstm]* batch_size) means batch_size num layers of LSTM cells
    # but keep it to 1 or 2 for computational efficiency
    cell = tf.contrib.rnn.MultiRNNCell([lstm]*2)
    initial_state = cell.zero_state(batch_size, tf.float32)
    initial_state = tf.identity(initial_state, 'initial_state')
    return (cell, initial_state)
    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_init_cell(get_init_cell)

Tests Passed


### Word Embedding
Apply embedding to `input_data` using TensorFlow.  Return the embedded sequence.

In [10]:
############
vocab_size = len(int_to_vocab)
embed_dim = 200 # Number of embedding features 

def get_embed(input_data, vocab_size, embed_dim):
    """
    Create embedding for <input_data>.
    :param input_data: TF placeholder for text input.
    :param vocab_size: Number of words in vocabulary.
    :param embed_dim: Number of embedding dimensions
    :return: Embedded input.
    """
    # TODO: Implement Function
    embedding = tf.Variable(tf.random_uniform((vocab_size, embed_dim), -1, 1))#embedding matrix
    embed = tf.nn.embedding_lookup(embedding, input_data)#embedding tensors
    
    return embed


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_embed(get_embed)

Tests Passed


### Build RNN
You created a RNN Cell in the `get_init_cell()` function.  Time to use the cell to create a RNN.
- Build the RNN using the [`tf.nn.dynamic_rnn()`](https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn)
 - Apply the name "final_state" to the final state using [`tf.identity()`](https://www.tensorflow.org/api_docs/python/tf/identity)

Return the outputs and final_state state in the following tuple `(Outputs, FinalState)` 

In [11]:
###############from https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn
""""tf.nn.dynamic_rnn(
    cell,
    inputs,
    sequence_length=None,
    initial_state=None,
    dtype=None,
    parallel_iterations=None,
    swap_memory=False,
    time_major=False,
    scope=None
)"""
#######################################################################################

def build_rnn(cell, inputs):
    """
    Create a RNN using a RNN Cell
    :param cell: RNN Cell
    :param inputs: Input text data
    :return: Tuple (Outputs, Final State)
    """
    # TODO: Implement Function
    Outputs, final_state = tf.nn.dynamic_rnn(cell, inputs, dtype = tf.float32, initial_state = None)
    FinalState = tf.identity(final_state, 'final_state')
    
    return Outputs, FinalState


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_rnn(build_rnn)

Tests Passed


### Build the Neural Network
Apply the functions you implemented above to:
- Apply embedding to `input_data` using your `get_embed(input_data, vocab_size, embed_dim)` function.
- Build RNN using `cell` and your `build_rnn(cell, inputs)` function.
- Apply a fully connected layer with a linear activation and `vocab_size` as the number of outputs.

Return the logits and final state in the following tuple (Logits, FinalState) 

In [12]:

def build_nn(cell, rnn_size, input_data, vocab_size, embed_dim):
    """
    Build part of the neural network
    :param cell: RNN cell
    :param rnn_size: Size of rnns???????????
    :param input_data: Input data
    :param vocab_size: Vocabulary size
    :param embed_dim: Number of embedding dimensions
    :return: Tuple (Logits, FinalState)
    """
    # TODO: Implement Function
    #apply embedding per above
    inputs = get_embed(input_data,vocab_size, embed_dim)
    #build RNN per above
    outputs, final_state = build_rnn(cell, inputs)
    
    #using tensorflow function and None for activation keeps it linear
    logits = tf.contrib.layers.fully_connected(outputs, vocab_size, activation_fn=None)
    
    
    return logits, final_state
    

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_build_nn(build_nn)

Tests Passed


In [13]:
### Batches
Implement `get_batches` to create batches of input and targets using `int_text`.  
The batches should be a Numpy array with the shape `(number of batches, 2, batch size, sequence length)`. 
Each batch contains two elements:
- The first element is a single batch of **input** with the shape `[batch size, sequence length]`
- The second element is a single batch of **targets** with the shape `[batch size, sequence length]`

If you can't fill the last batch with enough data, drop the last batch.

For example, `get_batches([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 3, 2)` 
would return a Numpy array of the following:
```
[
  # First Batch
  [
    # Batch of Input
    [[ 1  2], [ 7  8], [13 14]]
    # Batch of targets
    [[ 2  3], [ 8  9], [14 15]]
  ]

  # Second Batch
  [
    # Batch of Input
    [[ 3  4], [ 9 10], [15 16]]
    # Batch of targets
    [[ 4  5], [10 11], [16 17]]
  ]

  # Third Batch
  [
    # Batch of Input
    [[ 5  6], [11 12], [17 18]]
    # Batch of targets
    [[ 6  7], [12 13], [18  1]]
  ]
]
```

Notice that the last target value in the last batch is the first input value of the first batch. In this case, `1`. 
This is a common technique used when creating sequence batches, although it is rather unintuitive.

SyntaxError: invalid syntax (<ipython-input-13-aab1b0040526>, line 2)

In [14]:
def get_batches(int_text, batch_size, seq_length):#(array, batch_size (number of batches), (1,2,3),(4,5,6)
    """
    Return batches of input and target (shift targets over 1 and wrap around so first input is last target)
    :param int_text: Text with the words replaced by their ids (arr)
    :param batch_size: The size of batch
    :param seq_length: The length of sequence (n_steps)
    :return: Batches as a Numpy array
    """
    
    # TODO: Implement Function
     # Get the number of characters per batch and number of batches we can make
    chars_per_batch = batch_size * seq_length #128 * 5 =640
    n_batches = len(int_text)//chars_per_batch # 7 = 4480/640  probably gets floored to 7
    
    # Keep only enough characters to make full batches
    input_data = np.array(int_text[:n_batches * chars_per_batch])#int_text[:4480]
    print("int_text")
    print(int_text)#0 to 4479
    
    #roll over first x to last y
    
    target_data = np.roll(input_data, -1)#????sure
    
    #reshape and split input and target data
    input_batches = np.split(input_data.reshape(batch_size, -1), n_batches, 1)
    target_batches = np.split(target_data.reshape(batch_size, -1), n_batches, 1)
    
    #zip the above input and target batches
    #refer to https://stackoverflow.com/questions/13704860/zip-lists-in-python
    Batches = np.array(list(zip(input_batches, target_batches)))
    
    return Batches
#TODO:  read numpy and python documentation as a lot of this mimics what I saw in forums

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_batches(get_batches)

int_text
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 

## Neural Network Training
### Hyperparameters
Tune the following parameters:

- Set `num_epochs` to the number of epochs.
- Set `batch_size` to the batch size.
- Set `rnn_size` to the size of the RNNs.
- Set `embed_dim` to the size of the embedding.
- Set `seq_length` to the length of sequence.
- Set `learning_rate` to the learning rate.
- Set `show_every_n_batches` to the number of batches the neural network should print progress.

In [15]:
# Number of Epochs
num_epochs = 10
# Batch Size
batch_size = 128
# RNN Size should be more than the embed_dim(hidden layer size, suggested start at double)
rnn_size = 200
# Embedding Dimension Size (hidden layer)
embed_dim = 100
# Sequence Length
seq_length = 100
# Learning Rate
learning_rate = 0.01
# Show stats for every n number of batches
show_every_n_batches = 5
#numbers taken from discussion forums

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
save_dir = './save'

### Build the Graph
Build the graph using the neural network you implemented.

In [18]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
from tensorflow.contrib import seq2seq

train_graph = tf.Graph()
with train_graph.as_default():
    vocab_size = len(int_to_vocab)
    input_text, targets, lr = get_inputs()
    input_data_shape = tf.shape(input_text)
    cell, initial_state = get_init_cell(input_data_shape[0], rnn_size)
    logits, final_state = build_nn(cell, rnn_size, input_text, vocab_size, embed_dim)

    # Probabilities for generating words
    probs = tf.nn.softmax(logits, name='probs')

    # Loss function
    cost = seq2seq.sequence_loss(
        logits,
        targets,
        tf.ones([input_data_shape[0], input_data_shape[1]]))

    # Optimizer
    optimizer = tf.train.AdamOptimizer(lr)

    # Gradient Clipping
    gradients = optimizer.compute_gradients(cost)
    capped_gradients = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gradients if grad is not None]
    train_op = optimizer.apply_gradients(capped_gradients)

## Train
Train the neural network on the preprocessed data.  If you have a hard time getting a good loss, check the [forums](https://discussions.udacity.com/) to see if anyone is having the same problem.

In [19]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
batches = get_batches(int_text, batch_size, seq_length)

with tf.Session(graph=train_graph) as sess:
    sess.run(tf.global_variables_initializer())

    for epoch_i in range(num_epochs):
        state = sess.run(initial_state, {input_text: batches[0][0]})

        for batch_i, (x, y) in enumerate(batches):
            feed = {
                input_text: x,
                targets: y,
                initial_state: state,
                lr: learning_rate}
            train_loss, state, _ = sess.run([cost, final_state, train_op], feed)

            # Show every <show_every_n_batches> batches
            if (epoch_i * len(batches) + batch_i) % show_every_n_batches == 0:
                print('Epoch {:>3} Batch {:>4}/{}   train_loss = {:.3f}'.format(
                    epoch_i,
                    batch_i,
                    len(batches),
                    train_loss))

    # Save Model
    saver = tf.train.Saver()
    saver.save(sess, save_dir)
    print('Model Trained and Saved')

int_text
[9, 3, 121, 172, 4, 173, 332, 0, 137, 5, 2896, 513, 13, 145, 0, 1, 146, 174, 2, 36, 2, 212, 2, 22, 961, 79, 10, 203, 198, 2, 1170, 0, 1, 9, 3, 121, 172, 4, 379, 28, 2, 94, 267, 0, 3, 13, 604, 4, 961, 1170, 0, 961, 1170, 0, 29, 2, 175, 664, 299, 961, 1170, 2, 1440, 10, 1, 9, 3, 121, 172, 4, 220, 7, 87, 1441, 0, 60, 15, 185, 729, 24, 78, 962, 7, 2, 14, 24, 78, 1900, 16, 198, 28, 26, 72, 35, 84, 841, 423, 0, 1, 9, 147, 5, 316, 27, 10, 61, 62, 26, 842, 1901, 549, 0, 1, 12, 6, 54, 16, 514, 2, 30, 0, 161, 21, 233, 60, 0, 1, 9, 27, 2, 29, 2, 7, 186, 62, 145, 13, 470, 26, 514, 0, 1, 41, 36, 2, 7, 186, 152, 145, 13, 2897, 26, 1902, 2898, 0, 1, 1, 1, 9, 116, 2, 289, 18, 268, 0, 63, 2, 79, 22, 11, 2899, 83, 1171, 0, 1, 41, 71, 6, 153, 1903, 2, 550, 43, 25, 98, 0, 3, 843, 4, 1, 1, 1, 41, 29, 27, 2, 963, 26, 2900, 665, 380, 10, 1, 12, 605, 0, 75, 38, 1172, 79, 37, 155, 0, 964, 47, 11, 170, 307, 71, 75, 167, 424, 5, 184, 0, 3, 308, 4, 1, 9, 3, 1442, 35, 1904, 4, 1443, 2901, 2902, 8, 34, 230

Epoch   0 Batch    0/5   train_loss = 8.821
Epoch   1 Batch    0/5   train_loss = 6.187
Epoch   2 Batch    0/5   train_loss = 6.169
Epoch   3 Batch    0/5   train_loss = 6.126
Epoch   4 Batch    0/5   train_loss = 6.035
Epoch   5 Batch    0/5   train_loss = 5.988
Epoch   6 Batch    0/5   train_loss = 5.955
Epoch   7 Batch    0/5   train_loss = 5.950
Epoch   8 Batch    0/5   train_loss = 5.958
Epoch   9 Batch    0/5   train_loss = 5.963
Model Trained and Saved


## Save Parameters
Save `seq_length` and `save_dir` for generating a new TV script.

In [20]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
# Save parameters for checkpoint
helper.save_params((seq_length, save_dir))

# Checkpoint

In [2]:
"""
DON'T MODIFY ANYTHING IN THIS CELL
"""
import tensorflow as tf
import numpy as np
import helper
import problem_unittests as tests

_, vocab_to_int, int_to_vocab, token_dict = helper.load_preprocess()
seq_length, load_dir = helper.load_params()

/home/nobu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Instructions for updating:
Use the retry module or similar alternatives.


## Implement Generate Functions
### Get Tensors
Get tensors from `loaded_graph` using the function [`get_tensor_by_name()`](https://www.tensorflow.org/api_docs/python/tf/Graph#get_tensor_by_name).  Get the tensors using the following names:
- "input:0"
- "initial_state:0"
- "final_state:0"
- "probs:0"

Return the tensors in the following tuple `(InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)` 

In [3]:
def get_tensors(loaded_graph):
    """
    Get input, initial state, final state, and probabilities tensor from <loaded_graph>
    :param loaded_graph: TensorFlow graph loaded from file
    :return: Tuple (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    """
    # TODO: Implement Function
    #from https://discussions.udacity.com/t/stuck-with-the-get-tensor/234988
    
    InputTensor = loaded_graph.get_tensor_by_name("input:0")
    InitialStateTensor = loaded_graph.get_tensor_by_name("initial_state:0")
    FinalStateTensor = loaded_graph.get_tensor_by_name("final_state:0")
    ProbsTensor = loaded_graph.get_tensor_by_name("probs:0")
    
    return (InputTensor, InitialStateTensor, FinalStateTensor, ProbsTensor)
    


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_get_tensors(get_tensors)

Tests Passed


### Choose Word
Implement the `pick_word()` function to select the next word using `probabilities`.

In [6]:
def pick_word(probabilities, int_to_vocab):
    """
    Pick the next word in the generated text
    :param probabilities: Probabilites of the next word
    :param int_to_vocab: Dictionary of word ids as the keys and words as the values
    :return: String of the predicted word
    """
    # TODO: Implement Function
    print(probabilities)
    print(len(probabilities))
    
    #https://discussions.udacity.com/t/pick-word-passes-test-but-fails-latter/383468
    #probabilities is a list or matrix so just reshape into a vector
    #probabilities = probabilities.reshape((-1))
    print(probabilities)
    pick = np.random.choice(len(probabilities), p=probabilities)
    #print(pick)
    print(int_to_vocab[pick])
    return int_to_vocab[pick]
    
    #max of probability[i] is int_to_vocab[i]
    #next_word = int_to_vocab[i]
    #return next_word
    return None


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
tests.test_pick_word(pick_word)

[0.1  0.8  0.05 0.05]
4
[0.1  0.8  0.05 0.05]
is
Tests Passed


## Generate TV Script
This will generate the TV script for you.  Set `gen_length` to the length of TV script you want to generate.

In [7]:
gen_length = 200
# homer_simpson, moe_szyslak, or Barney_Gumble
prime_word = 'moe_szyslak'

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Load saved model
    loader = tf.train.import_meta_graph(load_dir + '.meta')
    loader.restore(sess, load_dir)

    # Get Tensors from loaded model
    input_text, initial_state, final_state, probs = get_tensors(loaded_graph)

    # Sentences generation setup
    gen_sentences = [prime_word + ':']
    prev_state = sess.run(initial_state, {input_text: np.array([[1]])})

    # Generate sentences
    for n in range(gen_length):
        # Dynamic Input
        dyn_input = [[vocab_to_int[word] for word in gen_sentences[-seq_length:]]]
        dyn_seq_length = len(dyn_input[0])

        # Get Prediction
        probabilities, prev_state = sess.run(
            [probs, final_state],
            {input_text: dyn_input, initial_state: prev_state})
        
        pred_word = pick_word(probabilities[dyn_seq_length-1], int_to_vocab)

        gen_sentences.append(pred_word)
    
    # Remove tokens
    tv_script = ' '.join(gen_sentences)
    for key, token in token_dict.items():
        ending = ' ' if key in ['\n', '(', '"'] else ''
        tv_script = tv_script.replace(' ' + token.lower(), key)
    tv_script = tv_script.replace('\n ', '\n')
    tv_script = tv_script.replace('( ', '(')
        
    print(tv_script)

'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
INFO:tensorflow:Restoring parameters from ./save
[4.6259388e-02 4.6169478e-02 2.5063613e-02 ... 5.6610812e-08 5.9898291e-08
 7.1226424e-08]
6779
[4.6259388e-02 4.6169478e-02 2.5063613e-02 ... 5.6610812e-08 5.9898291e-08
 7.1226424e-08]
isotopes
[8.4499836e-02 7.0730366e-02 4.6893679e-02 ... 3.4814334e-09 3.5354890e-09
 4.7579833e-09]
6779
[8.4499836e-02 7.0730366e-02 4.6893679e-02 ... 3.4814334e-09 3.5354890e-09
 4.7579833e-09]
fumes
[8.9136578e-02 7.0686854e-02 5.0243076e-02 ... 2.3570110e-09 2.4068707e-09
 3.2614313e-09]
6779
[8.9136578e-02 7.0686854e-02 5.0243076e-02 ... 2.3570110e-09 2.4068707e-09
 3.2614313e-09]
feel
[8.9242958e-02 6.9868594e-02 5.0582994e-02 ... 2.2494675e-09 2.3012006e-09
 3.1186893e-09]
6779
[8.9242958e-02 6.9868594e-02 5.0582994e-02 ... 2.2494675e-09 2.3012006e-09
 3.1186893e-09]
my
[8.9436114e-02 7.0030041e-02 5.0674133e-02 ... 2.2311895e-09 2.2825242e-09
 3.093968

[9.0228237e-02 7.1186207e-02 5.0864860e-02 ... 2.2082010e-09 2.2566424e-09
 3.0612493e-09]
6779
[9.0228237e-02 7.1186207e-02 5.0864860e-02 ... 2.2082010e-09 2.2566424e-09
 3.0612493e-09]
this
[9.1024987e-02 7.2325103e-02 5.1024321e-02 ... 2.1879611e-09 2.2342492e-09
 3.0319296e-09]
6779
[9.1024987e-02 7.2325103e-02 5.1024321e-02 ... 2.1879611e-09 2.2342492e-09
 3.0319296e-09]
like
[8.9602351e-02 7.0279844e-02 5.0729409e-02 ... 2.2238462e-09 2.2741615e-09
 3.0838558e-09]
6779
[8.9602351e-02 7.0279844e-02 5.0729409e-02 ... 2.2238462e-09 2.2741615e-09
 3.0838558e-09]
moe_szyslak:
[8.9603849e-02 7.0293218e-02 5.0734177e-02 ... 2.2232769e-09 2.2733713e-09
 3.0831249e-09]
6779
[8.9603849e-02 7.0293218e-02 5.0734177e-02 ... 2.2232769e-09 2.2733713e-09
 3.0831249e-09]
<period>
[9.4171152e-02 7.7048935e-02 5.1654413e-02 ... 2.1145385e-09 2.1530755e-09
 2.9258238e-09]
6779
[9.4171152e-02 7.7048935e-02 5.1654413e-02 ... 2.1145385e-09 2.1530755e-09
 2.9258238e-09]
want
[9.0749726e-02 7.1942702e-02

[8.9989558e-02 7.0820890e-02 5.0806683e-02 ... 2.2128062e-09 2.2618880e-09
 3.0679026e-09]
6779
[8.9989558e-02 7.0820890e-02 5.0806683e-02 ... 2.2128062e-09 2.2618880e-09
 3.0679026e-09]
it's
[9.0203665e-02 7.1118511e-02 5.0847270e-02 ... 2.2096596e-09 2.2586888e-09
 3.0631426e-09]
6779
[9.0203665e-02 7.1118511e-02 5.0847270e-02 ... 2.2096596e-09 2.2586888e-09
 3.0631426e-09]
rrrettturrrn
[9.2569508e-02 7.4642837e-02 5.1349510e-02 ... 2.1523008e-09 2.1945084e-09
 2.9804155e-09]
6779
[9.2569508e-02 7.4642837e-02 5.1349510e-02 ... 2.1523008e-09 2.1945084e-09
 2.9804155e-09]
the
[8.9287393e-02 6.9800697e-02 5.0650354e-02 ... 2.2317403e-09 2.2833142e-09
 3.0951275e-09]
6779
[8.9287393e-02 6.9800697e-02 5.0650354e-02 ... 2.2317403e-09 2.2833142e-09
 3.0951275e-09]
normal
[8.8458836e-02 6.8640739e-02 5.0474793e-02 ... 2.2535731e-09 2.3076840e-09
 3.1267362e-09]
6779
[8.8458836e-02 6.8640739e-02 5.0474793e-02 ... 2.2535731e-09 2.3076840e-09
 3.1267362e-09]
your
[8.9576110e-02 7.0227005e-02 5.

[9.0776235e-02 7.1942449e-02 5.0965380e-02 ... 2.1939968e-09 2.2411646e-09
 3.0405656e-09]
6779
[9.0776235e-02 7.1942449e-02 5.0965380e-02 ... 2.1939968e-09 2.2411646e-09
 3.0405656e-09]
right_paren
[9.0448275e-02 7.1515173e-02 5.0915163e-02 ... 2.2024427e-09 2.2500710e-09
 3.0529925e-09]
6779
[9.0448275e-02 7.1515173e-02 5.0915163e-02 ... 2.2024427e-09 2.2500710e-09
 3.0529925e-09]
rrrettturrrn
[9.2547879e-02 7.4610949e-02 5.1345445e-02 ... 2.1527176e-09 2.1949458e-09
 2.9810379e-09]
6779
[9.2547879e-02 7.4610949e-02 5.1345445e-02 ... 2.1527176e-09 2.1949458e-09
 2.9810379e-09]
beer
[9.1085717e-02 7.2433740e-02 5.1044099e-02 ... 2.1872255e-09 2.2332678e-09
 3.0309042e-09]
6779
[9.1085717e-02 7.2433740e-02 5.1044099e-02 ... 2.1872255e-09 2.2332678e-09
 3.0309042e-09]
have
[9.0630010e-02 7.1736909e-02 5.0937612e-02 ... 2.1973880e-09 2.2448343e-09
 3.0455154e-09]
6779
[9.0630010e-02 7.1736909e-02 5.0937612e-02 ... 2.1973880e-09 2.2448343e-09
 3.0455154e-09]
uh
[9.1821082e-02 7.3511176e-0

[9.3445614e-02 7.5964913e-02 5.1522486e-02 ... 2.1321152e-09 2.1722524e-09
 2.9512417e-09]
6779
[9.3445614e-02 7.5964913e-02 5.1522486e-02 ... 2.1321152e-09 2.1722524e-09
 2.9512417e-09]
had
[9.0924792e-02 7.2161004e-02 5.0997205e-02 ... 2.1895290e-09 2.2360849e-09
 3.0341774e-09]
6779
[9.0924792e-02 7.2161004e-02 5.0997205e-02 ... 2.1895290e-09 2.2360849e-09
 3.0341774e-09]
to
[9.0306655e-02 7.1312144e-02 5.0886150e-02 ... 2.2062032e-09 2.2542568e-09
 3.0584273e-09]
6779
[9.0306655e-02 7.1312144e-02 5.0886150e-02 ... 2.2062032e-09 2.2542568e-09
 3.0584273e-09]
left_paren
[8.7707900e-02 6.7588098e-02 5.0307196e-02 ... 2.2739888e-09 2.3307138e-09
 3.1561938e-09]
6779
[8.7707900e-02 6.7588098e-02 5.0307196e-02 ... 2.2739888e-09 2.3307138e-09
 3.1561938e-09]
it's
[8.9931250e-02 7.0729591e-02 5.0790761e-02 ... 2.2169726e-09 2.2668512e-09
 3.0737022e-09]
6779
[8.9931250e-02 7.0729591e-02 5.0790761e-02 ... 2.2169726e-09 2.2668512e-09
 3.0737022e-09]
works
[9.0693764e-02 7.1832031e-02 5.09516

# The TV Script is Nonsensical
It's ok if the TV script doesn't make any sense.  We trained on less than a megabyte of text.  In order to get good results, you'll have to use a smaller vocabulary or get more data.  Luckily there's more data!  As we mentioned in the beggining of this project, this is a subset of [another dataset](https://www.kaggle.com/wcukierski/the-simpsons-by-the-data).  We didn't have you train on all the data, because that would take too long.  However, you are free to train your neural network on all the data.  After you complete the project, of course.
# Submitting This Project
When submitting this project, make sure to run all the cells before saving the notebook. Save the notebook file as "dlnd_tv_script_generation.ipynb" and save it as a HTML file under "File" -> "Download as". Include the "helper.py" and "problem_unittests.py" files in your submission.